### ISSUE TITLE
Refactorisation de la fonction de filtrage des clients dans le formulaire de contrat

### ISSUE THREAD

**Issue by lpodev** [LPOdev/Sploks#1]
On a un if monstrueux, on doit pouvoir faire mieux!

**Comment by XCarrel** [comment]
for x in range(tbl_customers.rowCount()):
        match = False
        
        for y in range(tbl_customers.columnCount()):
            
            if tbl_customers.item(x,y).text().lower.find(critere[y]):
                match=true
                break

**Comment by lpodev** [comment]
La fonction a été complètement reformulée et est maintenant beaucoup plus logique et surtout beaucoup plus performante.
Une bonne différence au niveau de la vitesse de fonctionnement.

**Comment by lpodev** [comment]
Après la refactorisation de la fonction, j'ai remarqué que j'avais utilisé une fonctionnalité qui est disponible que à partir de Python 3.10. Cela cause soucis car PyQt5 n'est pas disponible sur la version Python 3.10 MacOs.

J'ai donc reformulé encore une fois la fonction.
